---
name: main

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  run-build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.24"
      - run: |
          uv run pre-commit run --all-files --show-diff-on-failure
      - run: >
          TAG=latest
          make build push
