---
name: main

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  run-build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          TAG=latest
          make build
          make push
